#!/bin/bash
curl https://kof-website-ziweigamepoch.c9users.io/news/news43 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news41  --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news39 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news8 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news5 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news7 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news31 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news5 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news7 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news31 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news5 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news7 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news36 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news41  --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news39 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news5 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news7 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news36 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news5 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news7 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news31 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news39 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news8 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news5 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news7 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news36 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news5 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news7 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news31 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news39 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news8 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news5 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news7 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news36 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news39 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news8 --silent
curl https://gamepoch-website-cn-ziweigamepoch.c9users.io/news/news5 --silent